### ISSUE TITLE
Dublicate children

### ISSUE THREAD

**Issue by TorbenMiller** [TriPed-Robot/trip_kinematics#65]
Calling the robot constructor duplicates the children of some of the groups.

**Comment by liquidcronos** [comment]
Please give an example of this error, I cant seem to see the problem with the code you intent to fix.

**Comment by TorbenMiller** [comment]
<script src="https://gist.github.com/TorbenMiller/2de379205fb49620532d1fe52eeb1ba7.js"></script>
